# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdf8183485f43b4bfc1cb6382fefb36723aaab35c0f4fac17407101ea74b9c12bebd8bd6809632b1569550c19e9a3a50aad7d70879c3fd1112f06e2432965ecd

test:
  secret_key_base: a3a67a483adb3c8c12e4d327535f1fb590312a2c453866e55ddc2e0b735e330a507cf84fef0e314dce198a23beb1f0030aef454f06737f6cc2be3a9187c39ced

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
